# Generated by Django 4.1.5 on 2023-02-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('MessageId', models.AutoField(primary_key=True, serialize=False)),
                ('fromUser', models.CharField(max_length=500)),
                ('toUser', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('emailId', models.CharField(max_length=500)),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
                ('profilePhotoUrl', models.CharField(max_length=500)),
            ],
        ),
    ]
